# version: 2016-12-20
---
- name: Configure F5 OpenStack LBaaSv2 Agent with AllowedAddressPairs for overcloud
  ini_file:
    dest: '{{ agent_ini_file }}'
    section: DEFAULT
    option: l3_binding_driver
    value: f5_openstack_agent.lbaasv2.drivers.bigip.l3_binding.AllowedAddressPairs
  when: not {{ undercloud }}

- name: Configure F5 OpenStack LBaaSv2 Agent to turn off Global Routed Mode for undercloud
  ini_file:
    dest: '{{ agent_ini_file }}'
    section: DEFAULT
    option: f5_global_routed_mode
    value: 'False'
  when: '{{ undercloud }}'

- name: Configure F5 OpenStack LBaaSv2 Agent set vtep selfip name for undercloud
  ini_file:
    dest: '{{ agent_ini_file }}'
    section: DEFAULT
    option: f5_vtep_selfip_name
    value: selfip.client
  when: '{{ undercloud }}'

- name: Configure F5 OpenStack LBaaSv2 Agent set advertised tunnel types for undercloud
  ini_file:
    dest: '{{ agent_ini_file }}'
    section: DEFAULT
    option: advertised_tunnel_types
    value: '{{ tunnel_types }}'
  when: '{{ undercloud }}'

- name: Configure F5 OpenStack LBaaSv2 Agent with icontrol_hostname
  ini_file:
    dest: '{{ agent_ini_file }}'
    section: DEFAULT
    option: icontrol_hostname
    value: '{{ bigip_netloc }}'

- name: Stop F5 OpenStack Agent in prep for restarting
  service:
    name: '{{ agent_service_name }}'
    state: stopped

- name: Disable F5 OpenStack Agent in prep for restarting
  service:
    name: '{{ agent_service_name }}'
    enabled: no

- name: Enable F5 OpenStack Agent
  service:
    name: '{{ agent_service_name }}'
    enabled: yes

- name: Start F5 OpenStack Agent
  service:
    name: '{{ agent_service_name }}'
    state: started