# version: 2017-04-20
---
- name: Install the icontrol-rest-python from rpm or deb package
  package:
    name: '{{ f5_icontrol_rest_python_pkg_location }}'
    state: present
  when: not use_pip|bool

- name: Install the f5-sdk from rpm or deb package
  package:
    name: '{{ f5_sdk_rpm_pkg_location }}'
    state: present
  when: not use_pip|bool

- name: Install the F5 OpenStack LBaaSv2 Agent from rpm or deb package
  package:
    name: '{{ agent_pkg_location }}'
    state: present
  when: not use_pip|bool

- name: Install the F5 OpenStack LBaaSv2 Agent with pip
  pip:
    name: '{{ agent_pkg_location }}'
    editable: false
  when: use_pip|bool and not pip_upgrade|bool

- name: Upgrade the F5 OpenStack LBaaSv2 Agent with pip
  pip:
    name: '{{ agent_pkg_location }}'
    editable: false
    extra_args: --upgrade
  when: use_pip|bool and pip_upgrade|bool
